-- Create database
CREATE DATABASE IF NOT EXISTS product_aggregator;
USE product_aggregator;

-- Create products table
CREATE TABLE IF NOT EXISTS products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    marca VARCHAR(100) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    descricao TEXT NOT NULL,
    imagem1 VARCHAR(500) NOT NULL,
    imagem2 VARCHAR(500) NOT NULL,
    link_externo VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert sample products
INSERT INTO products (nome, marca, categoria, descricao, imagem1, imagem2, link_externo) VALUES
('Tênis Nike Air Max Excee Masculino', 'Nike', 'Tênis', 'Entre no ritmo com o Nike Air Max Excee e os toques sutis de cores novas para um estilo que desafia o tempo. Inspirados no Nike Air Max 90, estes tênis dão um toque moderno ao ícone lendário, com linhas de design alongadas e proporções distorcidas.', 'https://imgnike-a.akamaihd.net/360x360/02732251A2.jpg', 'https://imgnike-a.akamaihd.net/360x360/02732251A6.jpg', 'https://www.nike.com.br/tenis-nike-air-max-excee-masculino-027322.html?cor=51&utm_source=share_copy&utm_medium=organic&utm_campaign=product&utm_content=cta_topo'),
('Tênis Nike SB Force 58 Masculino', 'Nike', 'Tênis', 'A melhor e mais recente novidade a aparecer nas ruas, o Nike SB Force 58 garante a durabilidade da forma da sola com a flexibilidade de um tênis vulcanizado. Feito de lona e suede e com acabamento perfurado, todo o look é carregado com o DNA de herança do basquete.', 'https://imgnike-a.akamaihd.net/360x360/011580IDA2.jpg', 'https://imgnike-a.akamaihd.net/360x360/011580IDA6.jpg', 'https://www.nike.com.br/tenis-nike-sb-force-58-masculino-011580.html?cor=ID&utm_source=share_copy&utm_medium=organic&utm_campaign=product&utm_content=cta_topo'),
('Suéter Masculino de Malha em Modelagem Regular', 'Lacoste', 'Jaqueta', 'Aconchegante e estilosa, a exclusiva Blusa Gola Alta Masculina de Algodão com Zíper é a peça funcional e versátil que irá te acompanhar em vários contextos, desde um passeio casual até eventos sofisticados.', 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dwd842122f/AH1957_166_20.jpg?imwidth=380&impolicy=pctp&imdensity=1', 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dwd842122f/AH1957_166_20.jpg?imwidth=380&impolicy=pctp&imdensity=1', 'https://www.lacoste.com/br/lacoste/masculino/vestuário/sueteres-moletons/3665926601846.html?color=166&utm_source=google&utm_campaign=[Monks][BR][Shopping]Geral&gad_source=4&gad_campaignid=23082444661&gclid=CjwKCAjwntHPBhAaEiwA_Xp6RiT2M-s9M8PnU-pLZ_eOuCw3La79xV1HGTAdlR7Xze-XL926WCD8CxoC8RMQAvD_BwE'),
('Casaco Masculino de Moletom com Decote Careca e Modelagem Clássica', 'Lacoste', 'Moleton', 'O Moletom de Algodão Lacoste é uma peça que personifica o estilo icônico da marca, combinando elegância com conforto em tecido macio e sustentável', 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw68e6b590/SH2662_031_24.jpg?imwidth=380&impolicy=pctp&imdensity=1', 'https://imagesa1.lacoste.com/dw/image/v2/BCWL_PRD/on/demandware.static/-/Sites-master/default/dw2566cc93/SH2662_031_33.jpg?imwidth=380&impolicy=pctp&imdensity=1', 'https://www.lacoste.com/br/lacoste/masculino/vestuário/sueteres-moletons/SH2662-23.html?color=031'),
('Calça Esportiva Firebird', 'Adidas', 'Calça', 'A calça esportiva Firebird é uma referência ao estilo clássico da marca, reimaginado para o estilo de vida atual', 'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/b2a4ff6d6e6c44a39e8f80a5b8a26631_9366/Calca_Esportiva_Firebird_Preto_KD8315_25_model.jpg', 'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/1651f914a4f0430490ed636fb21d1cf6_9366/Calca_Esportiva_Firebird_Preto_KD8315_21_model.jpg', 'https://www.adidas.com.br/calca-esportiva-firebird/KD8315.html?cm_mmc=AdieSEM_Google_PLA-_-Always_On-_-Shopping-_-KD8315-0004-_-dv:eCom-_-cn:Always_On-_-pc:Originals&cm_mmc1=BR&cm_mmc2=PLA-Multiple-Originals-Other-None-BR-LATAM-eCom-Paid_Search&cm_mmc=AdieSEM_Google_PLA-_-adidas-LAM-BR-Shopping-AllProducts-_-All+Products-_-PRODUCT_GROUP-_-&-_-ds_kid=293946777986-_-&-_-ds_agid=174050197584-_-&-_-dv:eCom&cm_mmc1=BR&cm_mmc2=&adicl_gclid=CjwKCAjwntHPBhAaEiwA_Xp6RozacGegvKTvtsFvDvUr-vUsv0Vswt8J0JYRVenMOGOQjH5gjAq-9BoCFewQAvD_BwE&gclsrc=aw.ds&gad_source=4&gad_campaignid=21686150573&gclid=CjwKCAjwntHPBhAaEiwA_Xp6RozacGegvKTvtsFvDvUr-vUsv0Vswt8J0JYRVenMOGOQjH5gjAq-9BoCFewQAvD_BwE'),
('Tênis Lite Racer 4.0', 'Adidas', 'Tênis', 'Elegante e arrojado, este tênis adidas é ideal para o seu dia a dia. A entressola Cloudfoam proporciona conforto imediato, acompanhando você desde a caminhada matinal até o brunch com os amigos e qualquer outra atividade ao longo do dia.', 'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/79158bcae8b24765a6dce97ed8b504c7_9366/Tenis_Lite_Racer_4.0_Preto_JJ7367_01_00_standard.jpg', 'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/178dde1cd5774a82be5fcb94a48c97e6_9366/Tenis_Lite_Racer_4.0_Preto_JJ7367_04_standard.jpg', 'https://www.adidas.com.br/tenis-lite-racer-4.0/JJ7367.html'),
('JAQUETA JEANS ADICOLOR FIREBIRD TRACK TOP', 'Adidas', 'Moletom', 'A Jaqueta Jeans Adicolor Firebird é uma nova versão de um clássico, dando um toque moderno a um design atemporal.', 'https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/cf3deb85af984d44be1731fc748a8d8e_9366/JAQUETA_JEANS_ADICOLOR_FIREBIRD_TRACK_TOP_Azul_KD1517_HM1.jpg', 'https://assets.adidas.com/images/h_2000,f_auto,q_auto,fl_lossy,c_fill,g_auto/7767430d5f524ae992f4155bad7eede4_9366/JAQUETA_JEANS_ADICOLOR_FIREBIRD_TRACK_TOP_Azul_KD1517_HM5.jpg', 'https://www.adidas.com.br/jaqueta-jeans-adicolor-firebird-track-top/KD1517.html?cm_mmc=AdieSEM_Google_PLA-_-Always_On-_-Shopping-_-KD1517-0002-_-dv:eCom-_-cn:Always_On-_-pc:Originals&cm_mmc1=BR&cm_mmc2=PLA-Multiple-Originals-Other-None-BR-LATAM-eCom-Paid_Search&cm_mmc=AdieSEM_Google_PLA-_-adidas-LAM-BR-PMAX-AllProducts-M-_-PMAX_AllProducts_AON-_--_-&-_-ds_kid=-_-&-_-ds_agid=-_-&-_-dv:eCom&cm_mmc1=BR&cm_mmc2=&adicl_gclid=CjwKCAjwntHPBhAaEiwA_Xp6RoR5eGw2hNSJFoPp52v23j9h_HKSA3F1O55kkzD33ijQ09lt3iLvAhoCFh4QAvD_BwE&gclsrc=aw.ds&gad_source=4&gad_campaignid=18218350464&gclid=CjwKCAjwntHPBhAaEiwA_Xp6RoR5eGw2hNSJFoPp52v23j9h_HKSA3F1O55kkzD33ijQ09lt3iLvAhoCFh4QAvD_BwE'),
('Jaqueta Corinthians Nike Total 90 Essential Anthem III Masculina', 'Nike', 'Jaqueta', 'A nova coleção do Timão não só resgata um elenco inesquecível, mas uma Era: a Era Total 90. Foi com esse design icônico, cravado no peito, que a gente mostrou pro mundo mais uma vez o que era ser Total Corinthians.', 'https://imgnike-a.akamaihd.net/360x360/061064IDA11.jpg', 'https://imgnike-a.akamaihd.net/360x360/061064IDA12.jpg', 'https://www.nike.com.br/jaqueta-corinthians-niketotal-90-essential-anthem-iii-masculina-061064.html?cor=ID&utm_source=share_copy&utm_medium=organic&utm_campaign=product&utm_content=cta_topo');


